### ISSUE TITLE
Improving the frontend UI of the page 

### ISSUE THREAD

**Issue by Bishal976** [Bishal976/GreenScreen-Project#1]
Improving the frontend UI of the Web page!
Improving the front of the page.
overall making it's UI more attractive to use for the users

**Comment by ankit-kaushal** [comment]
> Improving the frontend UI of the Web page! Improving the front of the page. overall making it's UI more attractive to use for the users

Please assign this to me. I can work on it.

**Comment by Bishal976** [comment]
Sure go ahead !

**Comment by Bishal976** [comment]
Good work @ankit-kaushal 
thanks for your pretty contribution
I am closing this issue!!!
